### PR TITLE
Chnages in Dockerfile for performance test

### PR DESCRIPTION
**Pull request by ketank-new**
## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by npanpaliya** [comment]
Do you think we could have used our runtime image Dockerfile (offcourse with addition of yum install perf) which would also have conda env created and packages installed from given channel (say GSA).?

**Comment by SiyaAmonkar** [comment]
> Do you think we could have used our runtime image Dockerfile (offcourse with addition of yum install perf) which would also have conda env created and packages installed from given channel (say GSA).?

**Comment by SiyaAmonkar** [comment]
We have created this docker file in such a way that we only have the opence env created and all the packages are installed later in the workflow for performance testing. We are creating separate images so that our current builders Dockerfiles remain intact only for builder purpose. Using runtime docker file will require args to be supplied everytime we use the image like env files which will  be quite tedious.

**Review by npanpaliya — APPROVED** [review]

**Comment by cdeepali** [comment]
I think we can have the files at the path - `open_ce/images/performance-test/p9/Dockerfile`

**Pull request merged**
