### PR TITLE
changes for OpenCE v1.7.0

### PR DESCRIPTION
**Pull request by cdeepali**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by cdeepali** [comment]
I will raise a follow up PR for documentation changes.

**Comment by npanpaliya** [comment]
I think we should update Builder version too to 11.0 with this PR.

**Comment by cdeepali** [comment]
Yes, version update is to be done.

**Review by alexlang74 — APPROVED** [review]

**Comment by cdeepali** [comment]
We found that we would still need system GCC for P10, hence added only part of the changes from here in https://github.com/open-ce/open-ce-builder/pull/131.

**Pull request closed without merging**
