### PR TITLE
build_fix

### PR DESCRIPTION
**Pull request by ritumd**
## Checklist before submitting

- [X] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description
conda version updated to 4.12

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by alexlang74 — APPROVED** [review]
Too bad we have to touch all these files just because conda made this strange 4.13 version...

**Review by npanpaliya — APPROVED** [review]

**Comment by npanpaliya** [comment]
In the PR workflow output, I see many packages failing due to conda pinned to 4.12. https://github.com/open-ce/open-ce-builder/runs/6666831529?check_suite_focus=true.
@ritumd - Please try building conda package of builder locally to see exact conflicts.

**Comment by alexlang74** [comment]
@npanpaliya Yes, good point!

**Comment by ritumd** [comment]
> In the PR workflow output, I see many packages failing due to conda pinned to 4.12. https://github.com/open-ce/open-ce-builder/runs/6666831529?check_suite_focus=true. @ritumd - Please try building conda package of builder locally to see exact conflicts.

yes checking for that

**Comment by cdeepali** [comment]
@npanpaliya Yes once this gets merged, builder will be updated to 10.0.2. The documentation section where we list the compatibility needs to be updated as well.

**Comment by ritumd** [comment]
closing this PR as raised new one for same.
[(https://github.com/open-ce/open-ce-builder/pull/126)]

**Pull request closed without merging**
