### PR TITLE
check CUDA_HOME; warn if version mismatch (or unset).

### PR DESCRIPTION
**Pull request by dncliss**
## Checklist before submitting

- [ x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/main/tests/) to validate this change?  

## Description

Moved from https://github.com/open-ce/open-ce/pull/319 due to project reorganization; for
https://github.com/open-ce/open-ce/issues/88

Checks if $CUDA_HOME set; sets to default `/usr/local/cuda` if not set.
Checks whether requested cudadev build version matches local version in CUDA_HOME.
Issues WARNING if not.
(Note: does not abort build (non-fatal) because: CI may build without $CUDA_HOME set such
that we set to default path, which isn't present on build system; we don't want this to prevent
the build from proceeding.)

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by dncliss** [comment]
This was moved from a PR in open-ce/open-ce (noted above previously).  But unfortunately I've not given it attention since then.  It had been reviewed already, and there had been two remaining comments left to be addressed:
From Nishidha:
`I think this call should be .... added into build_tree's constructor too so that it can be called once when build env command is triggered.`
And from Deepali:
`I think we can also add a test for the newly added functionality.`

**Comment by dncliss** [comment]
Oh....and....I never did finish this old PR!  Is it still desired?  Anyone still want it?

I won't delete it, just in case anyone wants to grab it and make a new PR of their own with this code as a starting point. But I will personally step back from it.

**Comment by alexlang74** [comment]
@npanpaliya @cdeepali - what should we do with this PR?

**Comment by npanpaliya** [comment]
I think we can close it as it is not must to have. We can anytime use the changes of this PR in case such requirement comes.

**Comment by alexlang74** [comment]
Thanks, closing

**Pull request closed without merging**
